from near_jsonrpc_models.account_id import AccountId
from near_jsonrpc_models.chunk_header_view import ChunkHeaderView
from near_jsonrpc_models.indexer_transaction_with_outcome import IndexerTransactionWithOutcome
from near_jsonrpc_models.receipt_view import ReceiptView
from pydantic import BaseModel
from pydantic import Field
from typing import List


class IndexerChunkView(BaseModel):
    author: AccountId
    header: ChunkHeaderView
    # Receipts that were processed instantly in the same chunk they were created.
    instant_receipts: List[ReceiptView] = Field(default_factory=lambda: [ReceiptView(**item) for item in []])
    # Receipts generated in this chunk from transactions with `signer_id`
    # equal to `receiver_id`.
    local_receipts: List[ReceiptView] = Field(default_factory=lambda: [ReceiptView(**item) for item in []])
    # Represents receipts generated by execution of the previous chunk.
    # Note that those are not the receipts executed by this chunk or even
    # targeting that shard.
    receipts: List[ReceiptView]
    transactions: List[IndexerTransactionWithOutcome]
