from near_jsonrpc_models.indexer_execution_outcome_with_optional_receipt import IndexerExecutionOutcomeWithOptionalReceipt
from near_jsonrpc_models.signed_transaction_view import SignedTransactionView
from pydantic import BaseModel


class IndexerTransactionWithOutcome(BaseModel):
    outcome: IndexerExecutionOutcomeWithOptionalReceipt
    transaction: SignedTransactionView
