from near_jsonrpc_models.error_wrapper_for_rpc_light_client_proof_error import ErrorWrapperForRpcLightClientProofError
from near_jsonrpc_models.rpc_light_client_chunk_execution_proof_response import RpcLightClientChunkExecutionProofResponse
from pydantic import BaseModel
from pydantic import RootModel
from typing import Union


class JsonRpcResponseForRpcLightClientChunkExecutionProofResponseAndRpcLightClientProofErrorResult(BaseModel):
    id: str
    jsonrpc: str
    result: RpcLightClientChunkExecutionProofResponse

class JsonRpcResponseForRpcLightClientChunkExecutionProofResponseAndRpcLightClientProofErrorError(BaseModel):
    id: str
    jsonrpc: str
    error: ErrorWrapperForRpcLightClientProofError

class JsonRpcResponseForRpcLightClientChunkExecutionProofResponseAndRpcLightClientProofError(RootModel[Union[JsonRpcResponseForRpcLightClientChunkExecutionProofResponseAndRpcLightClientProofErrorResult, JsonRpcResponseForRpcLightClientChunkExecutionProofResponseAndRpcLightClientProofErrorError]]):
    pass

