"""Auto-generated API mixin (generated by ClientGenerator).

This file contains APIMixin which provides generated API methods.
The runtime provides a NearBaseClient implementation (located in 'base_client')
that exposes `_call(...)`.
"""


from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from .base_client import NearBaseClient

import models


class APIMixin:


    async def experimental_call_function(self: "NearBaseClient", *, params: models.RpcCallFunctionRequest) -> models.RpcCallFunctionResponse:
        """
        Calls a view function on a contract and returns the result.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalCallFunction,
            response_model=models.JsonRpcResponseForRpcCallFunctionResponseAndRpcCallFunctionError,
            params=params,
        )

    async def experimental_changes(self: "NearBaseClient", *, params: models.RpcStateChangesInBlockByTypeRequest) -> models.RpcStateChangesInBlockResponse:
        """
        [Deprecated] Returns changes for a given account, contract or contract code for given block height or hash. Consider using changes instead.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalChanges,
            response_model=models.JsonRpcResponseForRpcStateChangesInBlockResponseAndRpcStateChangesError,
            params=params,
        )

    async def experimental_changes_in_block(self: "NearBaseClient", *, params: models.RpcStateChangesInBlockRequest) -> models.RpcStateChangesInBlockByTypeResponse:
        """
        [Deprecated] Returns changes in block for given block height or hash over all transactions for all the types. Includes changes like account_touched, access_key_touched, data_touched, contract_code_touched. Consider using block_effects instead
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalChangesInBlock,
            response_model=models.JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcStateChangesError,
            params=params,
        )

    async def experimental_congestion_level(self: "NearBaseClient", *, params: models.RpcCongestionLevelRequest) -> models.RpcCongestionLevelResponse:
        """
        Queries the congestion level of a shard. More info about congestion [here](https://near.github.io/nearcore/architecture/how/receipt-congestion.html?highlight=congestion#receipt-congestion)
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalCongestionLevel,
            response_model=models.JsonRpcResponseForRpcCongestionLevelResponseAndRpcChunkError,
            params=params,
        )

    async def experimental_genesis_config(self: "NearBaseClient") -> models.GenesisConfig:
        """
        [Deprecated] Get initial state and parameters for the genesis block. Consider genesis_config instead.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        params = models.GenesisConfigRequest.model_validate(None)
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalGenesisConfig,
            response_model=models.JsonRpcResponseForGenesisConfigAndGenesisConfigError,
            params=params,
        )

    async def experimental_light_client_block_proof(self: "NearBaseClient", *, params: models.RpcLightClientBlockProofRequest) -> models.RpcLightClientBlockProofResponse:
        """
        Returns the proofs for a transaction execution.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalLightClientBlockProof,
            response_model=models.JsonRpcResponseForRpcLightClientBlockProofResponseAndRpcLightClientProofError,
            params=params,
        )

    async def experimental_light_client_proof(self: "NearBaseClient", *, params: models.RpcLightClientExecutionProofRequest) -> models.RpcLightClientExecutionProofResponse:
        """
        Returns the proofs for a transaction execution.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalLightClientProof,
            response_model=models.JsonRpcResponseForRpcLightClientExecutionProofResponseAndRpcLightClientProofError,
            params=params,
        )

    async def experimental_maintenance_windows(self: "NearBaseClient", *, params: models.RpcMaintenanceWindowsRequest) -> models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcMaintenanceWindowsError:
        """
        [Deprecated] Returns the future windows for maintenance in current epoch for the specified account. In the maintenance windows, the node will not be block producer or chunk producer. Consider using maintenance_windows instead.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalMaintenanceWindows,
            response_model=models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcMaintenanceWindowsError,
            params=params,
        )

    async def experimental_protocol_config(self: "NearBaseClient", *, params: models.RpcProtocolConfigRequest) -> models.RpcProtocolConfigResponse:
        """
        A configuration that defines the protocol-level parameters such as gas/storage costs, limits, feature flags, other settings
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalProtocolConfig,
            response_model=models.JsonRpcResponseForRpcProtocolConfigResponseAndRpcProtocolConfigError,
            params=params,
        )

    async def experimental_receipt(self: "NearBaseClient", *, params: models.RpcReceiptRequest) -> models.RpcReceiptResponse:
        """
        Fetches a receipt by its ID (as is, without a status or execution outcome)
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalReceipt,
            response_model=models.JsonRpcResponseForRpcReceiptResponseAndRpcReceiptError,
            params=params,
        )

    async def experimental_split_storage_info(self: "NearBaseClient", *, params: models.RpcSplitStorageInfoRequest) -> models.RpcSplitStorageInfoResponse:
        """
        Contains the split storage information. More info on split storage [here](https://near-nodes.io/archival/split-storage-archival)
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalSplitStorageInfo,
            response_model=models.JsonRpcResponseForRpcSplitStorageInfoResponseAndRpcSplitStorageInfoError,
            params=params,
        )

    async def experimental_tx_status(self: "NearBaseClient", *, params: models.RpcTransactionStatusRequest) -> models.RpcTransactionResponse:
        """
        Queries status of a transaction by hash, returning the final transaction result and details of all receipts.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalTxStatus,
            response_model=models.JsonRpcResponseForRpcTransactionResponseAndRpcTransactionError,
            params=params,
        )

    async def experimental_validators_ordered(self: "NearBaseClient", *, params: models.RpcValidatorsOrderedRequest) -> models.JsonRpcResponseForArrayOfValidatorStakeViewAndRpcValidatorError:
        """
        Returns the current epoch validators ordered in the block producer order with repetition. This endpoint is solely used for bridge currently and is not intended for other external use cases.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalValidatorsOrdered,
            response_model=models.JsonRpcResponseForArrayOfValidatorStakeViewAndRpcValidatorError,
            params=params,
        )

    async def experimental_view_access_key(self: "NearBaseClient", *, params: models.RpcViewAccessKeyRequest) -> models.RpcViewAccessKeyResponse:
        """
        Returns information about a single access key for given account.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewAccessKey,
            response_model=models.JsonRpcResponseForRpcViewAccessKeyResponseAndRpcViewAccessKeyError,
            params=params,
        )

    async def experimental_view_access_key_list(self: "NearBaseClient", *, params: models.RpcViewAccessKeyListRequest) -> models.RpcViewAccessKeyListResponse:
        """
        Returns all access keys for a given account.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewAccessKeyList,
            response_model=models.JsonRpcResponseForRpcViewAccessKeyListResponseAndRpcViewAccessKeyListError,
            params=params,
        )

    async def experimental_view_account(self: "NearBaseClient", *, params: models.RpcViewAccountRequest) -> models.RpcViewAccountResponse:
        """
        Returns information about an account for given account_id.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewAccount,
            response_model=models.JsonRpcResponseForRpcViewAccountResponseAndRpcViewAccountError,
            params=params,
        )

    async def experimental_view_code(self: "NearBaseClient", *, params: models.RpcViewCodeRequest) -> models.RpcViewCodeResponse:
        """
        Returns the contract code (Wasm binary) deployed to the account.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewCode,
            response_model=models.JsonRpcResponseForRpcViewCodeResponseAndRpcViewCodeError,
            params=params,
        )

    async def experimental_view_gas_key(self: "NearBaseClient", *, params: models.RpcViewGasKeyRequest) -> models.RpcViewGasKeyResponse:
        """
        Returns information about a single gas key for given account.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewGasKey,
            response_model=models.JsonRpcResponseForRpcViewGasKeyResponseAndRpcViewGasKeyError,
            params=params,
        )

    async def experimental_view_gas_key_list(self: "NearBaseClient", *, params: models.RpcViewGasKeyListRequest) -> models.RpcViewGasKeyListResponse:
        """
        Returns all gas keys for a given account.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewGasKeyList,
            response_model=models.JsonRpcResponseForRpcViewGasKeyListResponseAndRpcViewGasKeyListError,
            params=params,
        )

    async def experimental_view_state(self: "NearBaseClient", *, params: models.RpcViewStateRequest) -> models.RpcViewStateResponse:
        """
        Returns the state (key-value pairs) of a contract based on the key prefix.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForExperimentalViewState,
            response_model=models.JsonRpcResponseForRpcViewStateResponseAndRpcViewStateError,
            params=params,
        )

    async def block(self: "NearBaseClient", *, params: models.RpcBlockRequest) -> models.RpcBlockResponse:
        """
        Returns block details for given height or hash
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForBlock,
            response_model=models.JsonRpcResponseForRpcBlockResponseAndRpcBlockError,
            params=params,
        )

    async def block_effects(self: "NearBaseClient", *, params: models.RpcStateChangesInBlockRequest) -> models.RpcStateChangesInBlockByTypeResponse:
        """
        Returns changes in block for given block height or hash over all transactions for all the types. Includes changes like account_touched, access_key_touched, data_touched, contract_code_touched.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForBlockEffects,
            response_model=models.JsonRpcResponseForRpcStateChangesInBlockByTypeResponseAndRpcStateChangesError,
            params=params,
        )

    async def broadcast_tx_async(self: "NearBaseClient", *, params: models.RpcSendTransactionRequest) -> models.CryptoHash:
        """
        [Deprecated] Sends a transaction and immediately returns transaction hash. Consider using send_tx instead.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForBroadcastTxAsync,
            response_model=models.JsonRpcResponseForCryptoHashAndRpcTransactionError,
            params=params,
        )

    async def broadcast_tx_commit(self: "NearBaseClient", *, params: models.RpcSendTransactionRequest) -> models.RpcTransactionResponse:
        """
        [Deprecated] Sends a transaction and waits until transaction is fully complete. (Has a 10 second timeout). Consider using send_tx instead.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForBroadcastTxCommit,
            response_model=models.JsonRpcResponseForRpcTransactionResponseAndRpcTransactionError,
            params=params,
        )

    async def changes(self: "NearBaseClient", *, params: models.RpcStateChangesInBlockByTypeRequest) -> models.RpcStateChangesInBlockResponse:
        """
        Returns changes for a given account, contract or contract code for given block height or hash.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForChanges,
            response_model=models.JsonRpcResponseForRpcStateChangesInBlockResponseAndRpcStateChangesError,
            params=params,
        )

    async def chunk(self: "NearBaseClient", *, params: models.RpcChunkRequest) -> models.RpcChunkResponse:
        """
        Returns details of a specific chunk. You can run a block details query to get a valid chunk hash.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForChunk,
            response_model=models.JsonRpcResponseForRpcChunkResponseAndRpcChunkError,
            params=params,
        )

    async def client_config(self: "NearBaseClient") -> models.RpcClientConfigResponse:
        """
        Queries client node configuration
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        params = models.RpcClientConfigRequest.model_validate(None)
        return await self._call(
            request_model=models.JsonRpcRequestForClientConfig,
            response_model=models.JsonRpcResponseForRpcClientConfigResponseAndRpcClientConfigError,
            params=params,
        )

    async def gas_price(self: "NearBaseClient", *, params: models.RpcGasPriceRequest) -> models.RpcGasPriceResponse:
        """
        Returns gas price for a specific block_height or block_hash. Using [null] will return the most recent block's gas price.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForGasPrice,
            response_model=models.JsonRpcResponseForRpcGasPriceResponseAndRpcGasPriceError,
            params=params,
        )

    async def genesis_config(self: "NearBaseClient") -> models.GenesisConfig:
        """
        Get initial state and parameters for the genesis block
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        params = models.GenesisConfigRequest.model_validate(None)
        return await self._call(
            request_model=models.JsonRpcRequestForGenesisConfig,
            response_model=models.JsonRpcResponseForGenesisConfigAndGenesisConfigError,
            params=params,
        )

    async def health(self: "NearBaseClient") -> models.JsonRpcResponseForNullableRpcHealthResponseAndRpcStatusError:
        """
        Returns the current health status of the RPC node the client connects to.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        params = models.RpcHealthRequest.model_validate(None)
        return await self._call(
            request_model=models.JsonRpcRequestForHealth,
            response_model=models.JsonRpcResponseForNullableRpcHealthResponseAndRpcStatusError,
            params=params,
        )

    async def light_client_proof(self: "NearBaseClient", *, params: models.RpcLightClientExecutionProofRequest) -> models.RpcLightClientExecutionProofResponse:
        """
        Returns the proofs for a transaction execution.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForLightClientProof,
            response_model=models.JsonRpcResponseForRpcLightClientExecutionProofResponseAndRpcLightClientProofError,
            params=params,
        )

    async def maintenance_windows(self: "NearBaseClient", *, params: models.RpcMaintenanceWindowsRequest) -> models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcMaintenanceWindowsError:
        """
        Returns the future windows for maintenance in current epoch for the specified account. In the maintenance windows, the node will not be block producer or chunk producer.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForMaintenanceWindows,
            response_model=models.JsonRpcResponseForArrayOfRangeOfUint64AndRpcMaintenanceWindowsError,
            params=params,
        )

    async def network_info(self: "NearBaseClient") -> models.RpcNetworkInfoResponse:
        """
        Queries the current state of node network connections. This includes information about active peers, transmitted data, known producers, etc.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        params = models.RpcNetworkInfoRequest.model_validate(None)
        return await self._call(
            request_model=models.JsonRpcRequestForNetworkInfo,
            response_model=models.JsonRpcResponseForRpcNetworkInfoResponseAndRpcNetworkInfoError,
            params=params,
        )

    async def next_light_client_block(self: "NearBaseClient", *, params: models.RpcLightClientNextBlockRequest) -> models.RpcLightClientNextBlockResponse:
        """
        Returns the next light client block.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForNextLightClientBlock,
            response_model=models.JsonRpcResponseForRpcLightClientNextBlockResponseAndRpcLightClientNextBlockError,
            params=params,
        )

    async def query(self: "NearBaseClient", *, params: models.RpcQueryRequest) -> models.RpcQueryResponse:
        """
        This module allows you to make generic requests to the network.  The `RpcQueryRequest` struct takes in a [`BlockReference`](https://docs.rs/near-primitives/0.12.0/near_primitives/types/enum.BlockReference.html) and a [`QueryRequest`](https://docs.rs/near-primitives/0.12.0/near_primitives/views/enum.QueryRequest.html).  The `BlockReference` enum allows you to specify a block by `Finality`, `BlockId` or `SyncCheckpoint`.  The `QueryRequest` enum provides multiple variants for performing the following actions:  - View an account's details  - View a contract's code  - View the state of an account  - View the `AccessKey` of an account  - View the `AccessKeyList` of an account  - Call a function in a contract deployed on the network.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForQuery,
            response_model=models.JsonRpcResponseForRpcQueryResponseAndRpcQueryError,
            params=params,
        )

    async def send_tx(self: "NearBaseClient", *, params: models.RpcSendTransactionRequest) -> models.RpcTransactionResponse:
        """
        Sends transaction. Returns the guaranteed execution status and the results the blockchain can provide at the moment.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForSendTx,
            response_model=models.JsonRpcResponseForRpcTransactionResponseAndRpcTransactionError,
            params=params,
        )

    async def status(self: "NearBaseClient") -> models.RpcStatusResponse:
        """
        Requests the status of the connected RPC node. This includes information about sync status, nearcore node version, protocol version, the current set of validators, etc.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        params = models.RpcStatusRequest.model_validate(None)
        return await self._call(
            request_model=models.JsonRpcRequestForStatus,
            response_model=models.JsonRpcResponseForRpcStatusResponseAndRpcStatusError,
            params=params,
        )

    async def tx(self: "NearBaseClient", *, params: models.RpcTransactionStatusRequest) -> models.RpcTransactionResponse:
        """
        Queries status of a transaction by hash and returns the final transaction result.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForTx,
            response_model=models.JsonRpcResponseForRpcTransactionResponseAndRpcTransactionError,
            params=params,
        )

    async def validators(self: "NearBaseClient", *, params: models.RpcValidatorRequest) -> models.RpcValidatorResponse:
        """
        Queries active validators on the network. Returns details and the state of validation on the blockchain.
        High-level method: returns the result model or raises NearClientError/NearRpcError/NearHttpError.
        """
        return await self._call(
            request_model=models.JsonRpcRequestForValidators,
            response_model=models.JsonRpcResponseForRpcValidatorResponseAndRpcValidatorError,
            params=params,
        )
